import type { WorkflowDraft } from './types';

export const SAMPLE_WORKFLOWS: WorkflowDraft[] = [
  {
    id: 'sample-vendor-contract',
    name: 'Vendor Contract Compliance',
    description: 'Match invoices, POs, and contracts to flag out-of-scope spend and duplicate billing.',
    category: 'Procurement Audit',
    tags: ['3-way match', 'contracts', 'procurement'],
    logicPrompt:
      'For each invoice, confirm that a matching PO exists and that the line items are within the active contract. Flag anything that fails tolerance, has no PO, or exceeds the contract scope.',
    inputs: [
      {
        id: 'invoices',
        name: 'Invoices',
        type: 'csv',
        description: 'Vendor invoices for the period under audit.',
        required: true,
        multiple: true,
        columns: ['Invoice No', 'Vendor', 'PO Ref', 'Amount', 'Line Item', 'Invoice Date'],
      },
      {
        id: 'pos',
        name: 'Purchase Orders',
        type: 'csv',
        description: 'Open and closed POs from the ERP.',
        required: true,
        columns: ['PO No', 'Vendor', 'Contract Ref', 'Amount', 'Line Item', 'Status'],
      },
      {
        id: 'contracts',
        name: 'Contracts Register',
        type: 'pdf',
        description: 'Signed master contracts and statements of work.',
        required: true,
        multiple: true,
        columns: ['Contract Ref', 'Vendor', 'Scope', 'Cap', 'End Date'],
      },
    ],
    steps: [
      {
        id: 's1',
        name: 'Extract contract terms',
        description: 'Parse cap, scope, and end-date from each contract PDF.',
        type: 'extract',
        dataFiles: ['contracts'],
      },
      {
        id: 's2',
        name: 'Match invoice to PO',
        description: 'Join invoices and POs on the PO reference and vendor.',
        type: 'compare',
        dataFiles: ['invoices', 'pos'],
      },
      {
        id: 's3',
        name: 'Validate against contract scope',
        description: 'For each matched PO, confirm the line is within contract scope and cap.',
        type: 'validate',
        dataFiles: ['pos', 'contracts'],
      },
      {
        id: 's4',
        name: 'Flag out-of-scope spend',
        description: 'Emit a flag for every invoice line failing the validation.',
        type: 'flag',
        dataFiles: ['invoices', 'pos', 'contracts'],
      },
    ],
    output: {
      type: 'flags',
      title: 'Out-of-scope spend flags',
      description: 'Invoice lines that do not tie back to an in-scope PO + contract.',
    },
  },
  {
    id: 'sample-fin-recon',
    name: 'Financial Statement Reconciliation',
    description: 'Tie the trial balance to the GL and bank statements for the close period.',
    category: 'Financial Audit',
    tags: ['reconciliation', 'GL', 'close'],
    logicPrompt:
      'Reconcile each TB account against GL postings and, where applicable, the bank statement. Flag variances above tolerance and any unposted transactions.',
    inputs: [
      {
        id: 'tb',
        name: 'Trial Balance',
        type: 'csv',
        description: 'Period-end trial balance export.',
        required: true,
        columns: ['Account', 'Description', 'Debit', 'Credit', 'Balance'],
      },
      {
        id: 'gl',
        name: 'General Ledger',
        type: 'csv',
        description: 'Full GL posting detail for the period.',
        required: true,
        columns: ['Posting Date', 'Account', 'Doc No', 'Amount', 'Reference'],
      },
      {
        id: 'bank',
        name: 'Bank Statements',
        type: 'pdf',
        description: 'Statements for cash accounts in the reconciliation scope.',
        required: false,
        multiple: true,
        columns: ['Date', 'Description', 'Amount', 'Running Balance'],
      },
    ],
    steps: [
      {
        id: 's1',
        name: 'Aggregate GL by account',
        description: 'Sum GL postings per account for the period.',
        type: 'calculate',
        dataFiles: ['gl'],
      },
      {
        id: 's2',
        name: 'Compare TB to GL',
        description: 'Tie trial balance account totals to the aggregated GL.',
        type: 'compare',
        dataFiles: ['tb', 'gl'],
      },
      {
        id: 's3',
        name: 'Reconcile cash accounts',
        description: 'Match GL cash postings to bank statement entries.',
        type: 'compare',
        dataFiles: ['gl', 'bank'],
      },
      {
        id: 's4',
        name: 'Summarize variances',
        description: 'Produce a ranked variance report with aging and amount.',
        type: 'summarize',
        dataFiles: ['tb', 'gl', 'bank'],
      },
    ],
    output: {
      type: 'table',
      title: 'Account reconciliation summary',
      description: 'One row per account with TB vs GL variance and cash reconciliation status.',
    },
  },
  {
    id: 'sample-ap-audit',
    name: 'Invoice Verification & AP Audit',
    description: 'Detect duplicate invoices, vendor-master anomalies, and off-policy GL coding.',
    category: 'Accounts Payable',
    tags: ['duplicates', 'vendor master', 'AP'],
    logicPrompt:
      'Scan invoices for near-duplicates (vendor + amount + date), validate each vendor against the master, and flag GL codings that violate the expense policy matrix.',
    inputs: [
      {
        id: 'invoices',
        name: 'AP Invoices',
        type: 'csv',
        description: 'Invoices posted in the period.',
        required: true,
        multiple: true,
        columns: ['Invoice No', 'Vendor ID', 'Amount', 'GL Account', 'Invoice Date', 'Entered By'],
      },
      {
        id: 'vendor_master',
        name: 'Vendor Master',
        type: 'sql',
        description: 'Active vendor master snapshot.',
        required: true,
        columns: ['Vendor ID', 'Name', 'Bank Account', 'Status', 'Created On'],
      },
      {
        id: 'policy',
        name: 'Expense Policy Matrix',
        type: 'csv',
        description: 'Allowed GL codings per vendor category and spend tier.',
        required: false,
        columns: ['Category', 'GL Account', 'Threshold', 'Approver'],
      },
    ],
    steps: [
      {
        id: 's1',
        name: 'Detect near-duplicate invoices',
        description: 'Fuzzy match on vendor, amount, and invoice date.',
        type: 'analyze',
        dataFiles: ['invoices'],
      },
      {
        id: 's2',
        name: 'Validate vendors',
        description: 'Every invoice vendor must exist and be active in the master.',
        type: 'validate',
        dataFiles: ['invoices', 'vendor_master'],
      },
      {
        id: 's3',
        name: 'Check GL coding vs policy',
        description: 'Compare posted GL codes to the policy matrix per vendor category.',
        type: 'compare',
        dataFiles: ['invoices', 'policy'],
      },
      {
        id: 's4',
        name: 'Flag exceptions',
        description: 'Emit one flag per violation with severity and amount at risk.',
        type: 'flag',
        dataFiles: ['invoices', 'vendor_master', 'policy'],
      },
    ],
    output: {
      type: 'flags',
      title: 'AP exceptions',
      description: 'Duplicate, unknown-vendor, and off-policy invoices.',
    },
  },
];
