import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  ArrowLeft, FileText, Plus,
  GripVertical, X, Eye, AlertTriangle,
  ClipboardCheck, PieChart, Type, BookOpen, ChevronDown,
  MessageSquare
} from 'lucide-react';
import { EXCEPTION_DATA, ACTION_TAKEN_DATA } from '../../data/mockData';
import { useToast } from '../shared/Toast';

interface SavedTemplate {
  id: string;
  name: string;
  desc: string;
  category: string;
  icon: string;
  sections: { name: string; icon: string }[];
}

interface Props {
  context: 'new' | 'action-report' | 'from-template' | null;
  onBack: () => void;
  initialTitle?: string;
  onSaveAsTemplate?: (template: SavedTemplate) => void;
  existingTemplateNames?: string[];
}

interface ReportSection {
  id: string;
  type: 'text' | 'chart' | 'exception-summary' | 'action-taken';
  title: string;
  content: string;
}

const AVAILABLE_BLOCKS = [
  { type: 'text' as const, label: 'Commentary', icon: Type, desc: 'Add text commentary section' },
  { type: 'chart' as const, label: 'Chart / Visualization', icon: PieChart, desc: 'Add a chart block' },
  { type: 'exception-summary' as const, label: 'Exception Summary', icon: AlertTriangle, desc: 'Summary of flagged exceptions' },
  { type: 'action-taken' as const, label: 'Action Taken Summary', icon: ClipboardCheck, desc: 'Risk owner actions and resolutions' },
];

function getInitialSections(context: Props['context']): ReportSection[] {
  if (context === 'action-report') {
    return [
      { id: 's-1', type: 'text', title: 'Executive Summary', content: 'This report summarizes exceptions identified by the Duplicate Invoice Detection workflow (Run #12) and actions taken by assigned risk owners.' },
      { id: 's-2', type: 'exception-summary', title: 'Exception Overview', content: `${EXCEPTION_DATA.length} exceptions flagged` },
      { id: 's-3', type: 'action-taken', title: 'Actions Taken', content: `${ACTION_TAKEN_DATA.length} actions recorded` },
      { id: 's-4', type: 'chart', title: 'Status Breakdown', content: 'Exception resolution status distribution' },
    ];
  }
  return [];
}

const TEMPLATE_CATEGORIES = ['Compliance', 'Risk', 'Controls', 'Analytics', 'Audit', 'Executive'];

const SECTION_TYPE_ICON: Record<ReportSection['type'], string> = {
  text: 'file-text',
  chart: 'bar-chart',
  'exception-summary': 'alert-triangle',
  'action-taken': 'check-circle',
};

export default function ReportBuilder({ context, onBack, initialTitle, onSaveAsTemplate, existingTemplateNames = [] }: Props) {
  const { addToast } = useToast();
  const [title, setTitle] = useState(initialTitle ?? (context === 'action-report' ? 'Action Taken Report — Duplicate Invoice Detection' : 'Untitled Audit Report'));
  const [sections, setSections] = useState<ReportSection[]>(getInitialSections(context));
  const [showPreview, setShowPreview] = useState(false);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const [showSaveTemplate, setShowSaveTemplate] = useState(false);
  const [templateName, setTemplateName] = useState('');
  const [templateDesc, setTemplateDesc] = useState('');
  const [templateCategory, setTemplateCategory] = useState('Compliance');
  const [showCategoryDropdown, setShowCategoryDropdown] = useState(false);
  const [templateThemeColor, setTemplateThemeColor] = useState('#6a12cd');
  const [templateHeader, setTemplateHeader] = useState('Confidential — For Internal Use Only');
  const [templateFooter, setTemplateFooter] = useState('Generated by Auditify Copilot');

  const addSection = (type: ReportSection['type']) => {
    const titles: Record<string, string> = {
      text: 'Commentary',
      chart: 'Chart / Visualization',
      'exception-summary': 'Exception Summary',
      'action-taken': 'Action Taken Summary',
    };
    setSections(prev => [...prev, {
      id: `s-${Date.now()}`,
      type,
      title: titles[type] || 'New Section',
      content: type === 'exception-summary' ? `${EXCEPTION_DATA.length} exceptions flagged` :
               type === 'action-taken' ? `${ACTION_TAKEN_DATA.length} actions recorded` : '',
    }]);
  };

  const removeSection = (id: string) => {
    setSections(prev => prev.filter(s => s.id !== id));
  };

  const handleDragStart = (e: React.DragEvent, index: number) => {
    e.dataTransfer.setData('text/plain', String(index));
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    setDragOverIndex(index);
  };

  const handleDrop = (e: React.DragEvent, toIndex: number) => {
    e.preventDefault();
    const fromIndex = parseInt(e.dataTransfer.getData('text/plain'));
    setSections(prev => {
      const next = [...prev];
      const [moved] = next.splice(fromIndex, 1);
      next.splice(toIndex, 0, moved);
      return next;
    });
    setDragOverIndex(null);
  };

  const handleGenerate = () => {
    addToast({ type: 'success', message: 'PDF generated successfully!' });
  };

  const sectionColor = (type: ReportSection['type']) => {
    const colors = {
      text: 'bg-paper-50 text-ink-500',
      chart: 'bg-brand-50 text-brand-700',
      'exception-summary': 'bg-high-50 text-high-700',
      'action-taken': 'bg-compliant-50 text-compliant-700',
    };
    return colors[type];
  };

  return (
    <div className="flex h-full bg-surface-2 overflow-hidden">
      {/* Main Canvas */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Top Bar */}
        <div className="border-b border-border-light bg-white flex items-center justify-between px-6 py-4 shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2.5">
              <div className="p-2 bg-primary/10 text-primary rounded-xl shrink-0"><FileText size={16} /></div>
              <div>
                <input
                  value={title}
                  onChange={e => setTitle(e.target.value)}
                  className="text-[15px] font-semibold text-text bg-transparent border-none outline-none focus:underline focus:decoration-primary/30 block w-full"
                />
                <p className="text-[11px] text-text-muted">Template Configuration</p>
              </div>
            </div>
          </div>
          <button
            onClick={() => setShowPreview(p => !p)}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[12px] font-medium transition-colors cursor-pointer ${
              showPreview ? 'bg-primary/10 text-primary' : 'text-text-secondary hover:bg-paper-50'
            }`}
          >
            <Eye size={13} />
            Preview
          </button>
        </div>

        {/* Preview Mode */}
        {showPreview && (
          <div className="flex-1 overflow-y-auto py-5 px-6">
            <div className="bg-white rounded-xl border border-border-light overflow-hidden shadow-sm">
              {/* Report Header */}
              <div className="px-8 py-4 flex items-center justify-between" style={{ background: `${templateThemeColor}15` }}>
                <div>
                  <div className="text-[11px] font-bold uppercase tracking-widest mb-0.5" style={{ color: templateThemeColor }}>{templateCategory}</div>
                  <div className="text-[18px] font-bold text-text">{title}</div>
                </div>
                <div className="text-right">
                  <div className="text-[10px] text-text-muted">{templateHeader}</div>
                  <div className="text-[10px] text-text-muted mt-0.5">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
                </div>
              </div>
              <div className="h-1 w-full" style={{ background: templateThemeColor }} />

              {/* Section Placeholders */}
              <div className="px-8 py-5 flex flex-col gap-5">
                {sections.length === 0 ? (
                  <div className="text-center py-10 text-[12px] text-text-muted">No sections added yet. Add report sections to see them here.</div>
                ) : sections.map(section => (
                  <div key={section.id}>
                    <div className="flex items-center gap-2 mb-2">
                      <div className="h-3 w-1 rounded-full" style={{ background: templateThemeColor }} />
                      <span className="text-[12px] font-bold text-text">{section.title}</span>
                    </div>
                    {section.type === 'text' && (
                      <div className="space-y-1.5 pl-3">
                        <div className="h-2 bg-text-muted/10 rounded w-full" />
                        <div className="h-2 bg-text-muted/10 rounded w-5/6" />
                        <div className="h-2 bg-text-muted/10 rounded w-4/5" />
                        <div className="h-2 bg-text-muted/10 rounded w-3/4" />
                      </div>
                    )}
                    {section.type === 'chart' && (
                      <div className="pl-3 h-20 rounded-lg border border-dashed border-border flex items-center justify-center gap-2" style={{ background: `${templateThemeColor}05` }}>
                        <PieChart size={16} style={{ color: templateThemeColor }} />
                        <span className="text-[11px] font-medium" style={{ color: templateThemeColor }}>Chart / Visualization</span>
                      </div>
                    )}
                    {section.type === 'exception-summary' && (
                      <div className="pl-3 space-y-1.5">
                        {[100, 80, 60, 90].map((w, i) => (
                          <div key={i} className="flex items-center gap-2">
                            <div className="h-2 rounded" style={{ width: `${w}%`, background: `${templateThemeColor}20` }} />
                          </div>
                        ))}
                      </div>
                    )}
                    {section.type === 'action-taken' && (
                      <div className="pl-3 space-y-1.5">
                        {[1,2,3].map(i => (
                          <div key={i} className="h-6 rounded border border-border-light flex items-center px-2 gap-2" style={{ background: `${templateThemeColor}05` }}>
                            <div className="w-2 h-2 rounded-full" style={{ background: templateThemeColor }} />
                            <div className="h-1.5 rounded bg-text-muted/15 flex-1" />
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>

              {/* Report Footer */}
              <div className="px-8 py-3 border-t border-border-light flex items-center justify-between" style={{ background: `${templateThemeColor}08` }}>
                <span className="text-[9px] text-text-muted">{templateFooter}</span>
                <span className="text-[9px] text-text-muted">Page 1 of 1</span>
              </div>
            </div>
          </div>
        )}

        {/* Canvas Area */}
        {!showPreview && <div className="flex-1 overflow-y-auto py-5 px-6">
          <div className="space-y-4">
            {/* Template Configuration Section */}
            <div className="mb-2">
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Template Name</label>
                  <input
                    value={title}
                    onChange={e => setTitle(e.target.value)}
                    className="w-full px-3 py-2 rounded-lg border border-border-light text-[12px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                  />
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Category</label>
                  <div className="relative">
                    <button
                      onClick={() => setShowCategoryDropdown(p => !p)}
                      className="w-full flex items-center justify-between px-3 py-2 rounded-lg border border-border-light text-[12px] text-text hover:border-primary/30 transition-colors cursor-pointer"
                    >
                      {templateCategory}
                      <ChevronDown size={12} className={`text-text-muted transition-transform ${showCategoryDropdown ? 'rotate-180' : ''}`} />
                    </button>
                  </div>
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Header Text</label>
                  <input value={templateHeader} onChange={e => setTemplateHeader(e.target.value)} className="w-full px-3 py-2 rounded-lg border border-border-light text-[12px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10" />
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Footer Text</label>
                  <input value={templateFooter} onChange={e => setTemplateFooter(e.target.value)} className="w-full px-3 py-2 rounded-lg border border-border-light text-[12px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10" />
                </div>
              </div>
              <div className="mb-3">
                <label className="text-[12px] font-semibold text-text block mb-1.5">Theme Color</label>
                <div className="flex gap-2">
                  {['#6a12cd', '#1a2744', '#0d9488', '#334155', '#dc2626'].map(c => (
                    <button
                      key={c}
                      onClick={() => setTemplateThemeColor(c)}
                      className={`w-8 h-8 border-2 transition-all cursor-pointer ${templateThemeColor === c ? 'border-text scale-110 shadow-md' : 'border-transparent'}`}
                      style={{ background: c, borderRadius: '8px' }}
                    />
                  ))}
                </div>
              </div>
              {/* Mini preview */}
              <div className="border border-border-light rounded-lg p-3 bg-surface-2">
                <div className="bg-white rounded-md shadow-sm border border-border-light overflow-hidden" style={{ aspectRatio: '8.5/3' }}>
                  <div className="h-5 flex items-center justify-between px-3" style={{ background: `${templateThemeColor}10` }}>
                    <span className="text-[6px] font-bold" style={{ color: templateThemeColor }}>{title}</span>
                    <span className="text-[5px] text-text-muted">{templateHeader}</span>
                  </div>
                  <div className="p-2 flex-1">
                    <div className="h-1.5 w-16 bg-text-muted/15 rounded mb-0.5" />
                    <div className="h-1 w-full bg-text-muted/10 rounded mb-0.5" />
                    <div className="h-1 w-3/4 bg-text-muted/10 rounded" />
                  </div>
                  <div className="h-3 bg-surface-2 flex items-center justify-center">
                    <span className="text-[4px] text-text-muted">{templateFooter}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Add Report Sections */}
            <div>
              <h4 className="text-[12px] font-bold text-text-muted mb-3 flex items-center gap-2">
                <Plus size={13} className="text-primary" /> Add Report Sections
              </h4>
              <div className="flex flex-col gap-2">
                {AVAILABLE_BLOCKS.filter(b => b.type !== 'action-taken' || context === 'action-report').map(block => (
                  <button
                    key={block.type}
                    onClick={() => addSection(block.type)}
                    className="text-left p-3 rounded-xl border border-border-light hover:border-primary/30 hover:bg-primary-xlight/50 hover:shadow-sm transition-all duration-300 cursor-pointer group"
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <div className={`p-1 rounded-md ${sectionColor(block.type)}`}>
                        <block.icon size={12} />
                      </div>
                      <span className="text-[12px] font-semibold text-text group-hover:text-primary transition-colors">{block.label}</span>
                    </div>
                    <p className="text-[11px] text-text-muted pl-7">{block.desc}</p>
                  </button>
                ))}
              </div>
              <button
                onClick={() => {
                  const trimmed = title.trim();
                  if (!trimmed) {
                    addToast({ type: 'error', message: 'Template name cannot be empty.' });
                    return;
                  }
                  if (existingTemplateNames.some(n => n.toLowerCase() === trimmed.toLowerCase())) {
                    addToast({ type: 'error', message: `A template named "${trimmed}" already exists. Choose a different name.` });
                    return;
                  }
                  onSaveAsTemplate?.({
                    id: `ct-saved-${Date.now()}`,
                    name: trimmed,
                    desc: 'User-saved template',
                    category: 'Audit',
                    icon: 'file-text',
                    sections: sections.map(s => ({ name: s.title, icon: SECTION_TYPE_ICON[s.type] })),
                  });
                  addToast({ type: 'success', message: `${trimmed} has been saved to custom templates` });
                }}
                className="mt-3 w-full flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl border border-dashed border-border text-[12px] font-medium text-text-secondary hover:bg-paper-50 hover:border-primary/30 transition-colors cursor-pointer"
              >
                <BookOpen size={13} />
                Save as Template
              </button>
            </div>

            {sections.length > 0 && (
              <h4 className="text-[12px] font-bold text-text-muted px-1 pt-2">Detected Sections</h4>
            )}

            <AnimatePresence>
              {sections.map((section, index) => (
                <motion.div
                  key={section.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                >
                <div
                  className={`bg-white rounded-xl border shadow-sm hover:border-primary/20 transition-all duration-300 ${
                    dragOverIndex === index ? 'border-primary border-2' : 'border-border-light'
                  }`}
                  draggable
                  onDragStart={e => handleDragStart(e, index)}
                  onDragOver={e => handleDragOver(e, index)}
                  onDrop={e => handleDrop(e, index)}
                  onDragLeave={() => setDragOverIndex(null)}
                >
                  <div className="flex items-center gap-3 px-4 py-3 border-b border-border-light">
                    <div className="cursor-grab active:cursor-grabbing text-text-muted/40 hover:text-text-muted transition-colors">
                      <GripVertical size={14} />
                    </div>
                    <div className="w-6 h-6 rounded-lg bg-primary/10 text-primary text-[11px] font-bold flex items-center justify-center shrink-0">
                      {index + 1}
                    </div>
                    <input
                      value={section.title}
                      onChange={e => setSections(prev => prev.map(s => s.id === section.id ? { ...s, title: e.target.value } : s))}
                      className="flex-1 text-[13px] font-semibold text-text bg-transparent border-none outline-none"
                    />
                    <button onClick={() => removeSection(section.id)} className="p-1 hover:bg-risk-50 hover:text-risk-700 rounded text-text-muted transition-colors cursor-pointer">
                      <X size={13} />
                    </button>
                  </div>

                  <div className="px-4 py-3">
                    {section.type === 'text' ? (
                      <div className="flex items-center gap-2 p-3 bg-surface-2 rounded-lg">
                        <MessageSquare size={14} className="text-text-muted shrink-0" />
                        <div>
                          <div className="text-[12px] text-text-muted">Content added from /chat</div>
                          {section.content && <div className="text-[12px] text-text-secondary mt-0.5">{section.content}</div>}
                        </div>
                      </div>
                    ) : section.type === 'exception-summary' ? (
                      <div className="space-y-2">
                        <div className="flex gap-3">
                          <div className="flex-1 p-2.5 bg-risk-50 rounded-lg text-center">
                            <div className="text-[16px] font-bold text-risk-700">8</div>
                            <div className="text-[12px] text-risk-700 uppercase font-semibold">Flagged</div>
                          </div>
                          <div className="flex-1 p-2.5 bg-high-50 rounded-lg text-center">
                            <div className="text-[16px] font-bold text-high-700">3</div>
                            <div className="text-[12px] text-high-700 uppercase font-semibold">Assigned</div>
                          </div>
                          <div className="flex-1 p-2.5 bg-compliant-50 rounded-lg text-center">
                            <div className="text-[16px] font-bold text-compliant-700">1</div>
                            <div className="text-[12px] text-compliant-700 uppercase font-semibold">Resolved</div>
                          </div>
                        </div>
                        <div className="text-[12px] text-text-muted">Total flagged amount: $616,650</div>
                      </div>
                    ) : section.type === 'action-taken' ? (
                      <div className="overflow-x-auto">
                        <table className="w-full text-[12px]">
                          <thead>
                            <tr className="bg-surface-2">
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Exception</th>
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Action By</th>
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Date</th>
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Resolution</th>
                            </tr>
                          </thead>
                          <tbody>
                            {ACTION_TAKEN_DATA.map(a => (
                              <tr key={a.exceptionId} className="border-t border-border-light">
                                <td className="px-2 py-1.5 font-mono text-text-muted">{a.exceptionId}</td>
                                <td className="px-2 py-1.5 text-text">{a.actionBy}</td>
                                <td className="px-2 py-1.5 text-text-muted">{a.actionDate}</td>
                                <td className="px-2 py-1.5 text-text">{a.resolution}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    ) : section.type === 'chart' ? (
                      <div className="flex items-center justify-center h-24 bg-surface-2 rounded-lg">
                        <div className="flex items-end gap-1 h-14">
                          {[40, 65, 25, 80, 55, 70].map((h, i) => (
                            <div key={i} className="w-6 rounded-t" style={{ height: `${h}%`, background: `rgba(106,18,205,${0.15 + (h / 200)})` }} />
                          ))}
                        </div>
                      </div>
                    ) : null}
                  </div>
                </div>
                </motion.div>
              ))}
            </AnimatePresence>

          </div>
        </div>}

        {/* Footer */}
        <div className="px-6 py-4 border-t border-border-light bg-white shrink-0 flex items-center justify-between">
          <button onClick={onBack} className="flex items-center gap-1.5 px-4 py-2 rounded-lg border border-border text-[13px] font-semibold text-text-secondary hover:bg-paper-50 transition-colors cursor-pointer" style={{ borderRadius: '8px' }}>
            <ArrowLeft size={13} />
            Back
          </button>
          <button
            onClick={handleGenerate}
            className="flex items-center gap-1.5 px-4 py-2 bg-gradient-to-r from-primary to-primary-medium text-white text-[13px] font-semibold hover:from-primary-hover hover:to-primary transition-all cursor-pointer" style={{ borderRadius: '8px' }}
          >
            Generate Report
          </button>
        </div>
      </div>

      {/* Save as Template Modal */}
      <AnimatePresence>
        {showSaveTemplate && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center"
            onClick={() => setShowSaveTemplate(false)}
          >
            <div className="absolute inset-0 bg-black/20 backdrop-blur-sm" />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative bg-white rounded-2xl shadow-2xl w-[420px] overflow-hidden"
              onClick={e => e.stopPropagation()}
            >
              <div className="px-5 py-4 border-b border-border-light flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 bg-primary/10 text-primary rounded-lg"><BookOpen size={14} /></div>
                  <h4 className="text-[14px] font-semibold text-text">Save as Template</h4>
                </div>
                <button onClick={() => setShowSaveTemplate(false)} className="p-1 hover:bg-paper-50 rounded-lg cursor-pointer">
                  <X size={14} className="text-text-muted" />
                </button>
              </div>
              <div className="p-5 space-y-4">
                <div>
                  <label className="text-[12px] font-semibold text-text mb-1.5 block">Template Name</label>
                  <input
                    value={templateName}
                    onChange={e => setTemplateName(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-xl border border-border-light text-[13px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                    placeholder="Enter template name"
                  />
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text mb-1.5 block">Description</label>
                  <textarea
                    value={templateDesc}
                    onChange={e => setTemplateDesc(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-xl border border-border-light text-[13px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10 resize-none min-h-[70px]"
                    placeholder="Describe what this template is for..."
                  />
                </div>
                <div className="relative">
                  <label className="text-[12px] font-semibold text-text mb-1.5 block">Category</label>
                  <button
                    onClick={() => setShowCategoryDropdown(p => !p)}
                    className="w-full flex items-center justify-between px-3 py-2.5 rounded-xl border border-border-light text-[13px] text-text hover:border-primary/30 transition-colors cursor-pointer"
                  >
                    {templateCategory}
                    <ChevronDown size={14} className={`text-text-muted transition-transform ${showCategoryDropdown ? 'rotate-180' : ''}`} />
                  </button>
                  <AnimatePresence>
                    {showCategoryDropdown && (
                      <motion.div
                        initial={{ opacity: 0, y: -5 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -5 }}
                        className="absolute left-0 right-0 top-full mt-1 bg-white rounded-xl shadow-xl border border-border-light z-10 overflow-hidden"
                      >
                        {TEMPLATE_CATEGORIES.map(cat => (
                          <button
                            key={cat}
                            onClick={() => { setTemplateCategory(cat); setShowCategoryDropdown(false); }}
                            className={`w-full text-left px-3 py-2 text-[12px] hover:bg-primary-xlight transition-colors cursor-pointer ${templateCategory === cat ? 'text-primary font-semibold bg-primary/5' : 'text-text'}`}
                          >
                            {cat}
                          </button>
                        ))}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </div>
              <div className="px-5 py-4 border-t border-border-light flex justify-end gap-2">
                <button onClick={() => setShowSaveTemplate(false)} className="px-4 py-2 text-[12px] font-medium text-text-secondary hover:bg-paper-50 rounded-lg transition-colors cursor-pointer">Cancel</button>
                <button
                  onClick={() => { addToast({ type: 'success', message: 'Template saved to library!' }); setShowSaveTemplate(false); }}
                  className="px-5 py-2 bg-primary text-white rounded-xl text-[12px] font-semibold hover:bg-primary-hover transition-colors cursor-pointer"
                >
                  Save Template
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
}
